run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - gocyclo
    - gocritic
    - revive

linters-settings:
  misspell:
    locale: US
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: blank-imports
      - name: exported
      - name: unreachable-code
      - name: dot-imports
